# Generated by Django 5.1.3 on 2025-11-14 01:00

import django.db.models.deletion
import vehiculo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('Volkswagen', 'Volkswagen'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Mazda', 'Mazda'), ('Subaru', 'Subaru'), ('Lexus', 'Lexus'), ('Porsche', 'Porsche'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Volvo', 'Volvo'), ('Acura', 'Acura'), ('Infiniti', 'Infiniti')], max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condicion', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Seminuevo', 'Seminuevo')], default='Usado', max_length=20)),
                ('kilometraje', models.IntegerField(help_text='Kilometraje en km')),
                ('transmision', models.CharField(choices=[('Manual', 'Manual'), ('Automática', 'Automática'), ('CVT', 'CVT'), ('Semiautomática', 'Semiautomática')], max_length=20)),
                ('combustible', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Eléctrico', 'Eléctrico'), ('Gas Natural', 'Gas Natural')], max_length=20)),
                ('categoria', models.CharField(choices=[('Sedán', 'Sedán'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupé', 'Coupé'), ('Convertible', 'Convertible'), ('Pick-up', 'Pick-up'), ('Van', 'Van'), ('Deportivo', 'Deportivo'), ('Familiar', 'Familiar'), ('Crossover', 'Crossover')], max_length=20)),
                ('color', models.CharField(choices=[('Blanco', 'Blanco'), ('Negro', 'Negro'), ('Plata', 'Plata'), ('Gris', 'Gris'), ('Azul', 'Azul'), ('Rojo', 'Rojo'), ('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Naranja', 'Naranja'), ('Marrón', 'Marrón'), ('Dorado', 'Dorado'), ('Otro', 'Otro')], max_length=20)),
                ('puertas', models.IntegerField(default=4)),
                ('serial_carroceria', models.CharField(max_length=100, unique=True)),
                ('serial_motor', models.CharField(max_length=100, unique=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('motor', models.CharField(help_text='Ej: 2.0L Turbo', max_length=50)),
                ('potencia', models.CharField(blank=True, help_text='Ej: 150 HP', max_length=20, null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to=vehiculo.models.vehiculo_image_path)),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to=vehiculo.models.vehiculo_image_path)),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to=vehiculo.models.vehiculo_image_path)),
                ('imagen_4', models.ImageField(blank=True, null=True, upload_to=vehiculo.models.vehiculo_image_path)),
                ('imagen_5', models.ImageField(blank=True, null=True, upload_to=vehiculo.models.vehiculo_image_path)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('caracteristicas', models.TextField(blank=True, help_text='Características adicionales separadas por comas', max_length=500, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
